### ISSUE TITLE
Crashed during a preview

### ISSUE THREAD

**Issue by JannesRunge** [NeoArmageddon/MapBuilder#18]
Sometimes Arma 3 crashes when I look at the objects. No matter what. After approximately 15 minutes it crashes. Especially in de past walls it has happened more often. I have a minidump. In the RPT Log Incidentally, there is nothing to be found. 

https://mega.co.nz/#!FhFU3JaC   minidump
https://mega.co.nz/#!AhdBjKDb   .rpt-log

**Comment by NeoArmageddon** [comment]
The problem are the objects you are trying to preview. There are objects in your config without model.

**Comment by JannesRunge** [comment]
But these Objects i try to see are default arma 3 objects. Are you sure this cause the crash?

**Comment by NeoArmageddon** [comment]
Yes, I had this before. Are you accessing the objects from "Config" or from "Library"?

**Comment by JannesRunge** [comment]
I'm trying accessing the objects from the library -> A3 -> ...

**Comment by NeoArmageddon** [comment]
Which objects?

**Comment by JannesRunge** [comment]
Walls, Houses etc. some objects cause the crash. I make a video in 15 minutes to show you

**Comment by JannesRunge** [comment]
or i look what the classnames are - i dont have them yet

**Comment by JannesRunge** [comment]
Here the video:
https://www.youtube.com/watch?v=1d4U1QUecHQ

**Comment by NeoArmageddon** [comment]
Thanks, will look into this issue tomorrow.

**Comment by NeoArmageddon** [comment]
Are you using A3 Dev-Branch?

**Comment by JannesRunge** [comment]
no - i use the normal Offical release-Branch

**Comment by JannesRunge** [comment]
![nope](https://cloud.githubusercontent.com/assets/10133455/6750092/2bebf1cc-cef7-11e4-9944-52fbeafff27e.PNG) Some more Objects where the preview cause a crash.

**Comment by NeoArmageddon** [comment]
Works for me as expected. Only had crashes with a few ruins from A2.

**Comment by JannesRunge** [comment]
Okay, but why i have a Crash when i during a preview of the Object. Do you have an idea?

**Comment by NeoArmageddon** [comment]
You are right, the fs_xxx objects are broken, the fuelstation itself works. You also can't create the fs objects by script, looks like the models are broken or used as helperobjects for the actual fuel station.

**Comment by JannesRunge** [comment]
Okay, nice to know. But you said that all the other buildings works for you, you know why my client crash on these buildings? Should i reinstall my Arma 3?

**Comment by NeoArmageddon** [comment]
No, try to revalidate the files via steam (right click on your A3 -> properties -> local files -> validate).

I will investigate this further and will search for a solution on addon side.

**Comment by JannesRunge** [comment]
Already done - Nothing wrong.. I think i try to reinstall Arma 3 in 1-2 hours. First i try all Objects from Arma 3 Default with MapBuilder. Thanks for your help, if i will found some issues i will post them here :)

**Comment by NeoArmageddon** [comment]
No need to reinstall A3, I don't think your files are corrupted. Probably more a problem with your setup and the models itself (RAM, GRAM, graphicscard). Better look for other "breaking" objects and compile a list for me.

I tested nearly all objects by scrolling fast through the list, might be too fast to cause a crash, when the issue is a renderproblem.

**Comment by JannesRunge** [comment]
Okay, then i don't reinstall it. I test all the objects and i will do all corrupt objects into a list for you.

**Comment by NeoArmageddon** [comment]
The BIS object dialog was the problem. Some p3ds can't be shown there. 0.7.3 now uses RTT.
