### ISSUE TITLE
Clumsy option selection with mouse

### ISSUE THREAD

**Issue by Metalica** [NeoArmageddon/MapBuilder#23]
Problem:

 When i wanna select item and turn it 90°, it goes super speed and/or goes on the opositive direction. Im doing  sometimes 1 thing, 3-6 times.

 Solution:

 Add soft like pointers, where the item is turning and add option. To fine tune the speed of the object, which you wanna place (height, picth, etc......).

**Comment by NeoArmageddon** [comment]
Rotation of objects works perfect fine for everybody I talked to.

Either your mouse settings are fubar or you have a serious bug there. Post a video, when you thinkt he second one is the case.
