### ISSUE TITLE
RC 0.7 Feedback

### ISSUE THREAD

**Issue by Twelvecaliber** [NeoArmageddon/MapBuilder#7]
Just to clarify, these are some overall things i have found so far, only been tested in a multiplayer session.

Overall found the fencer good very useful, though sometimes when placing the fences created did not stay at a consistent height. 

Selection is much better now. Some issues with objects not deselecting when clicking on open ground though, and objects staying selected.

When placing fences and some other objects the additional yellow bounding line things, seem to draw off towards [0,0,0]

After a random period of time, selecting an object caused it to disappear, requiring the mission to be restarted. 

Pressing place in the fencer with no direction selected returned a script error. 

The new library interface is nice and cleaner, however things from the "Objects" category do not seem to be accessible now, there was no expandable drop down in the library list for them.

**Comment by NeoArmageddon** [comment]
Thanks for the feedback. I already know some of these problems but some are new. I will try to get things working before a update release.

**Comment by NeoArmageddon** [comment]
Most stuff should be fixed in current 1.7 branch
