### ISSUE TITLE
Bug: PitchBank problem on load (especially with terrain normal alignment)

### ISSUE THREAD

**Issue by Engelhjo** [NeoArmageddon/MapBuilder#8]
When using the fencer for placing fences (no shit, sherlock) and then reloading it, the objects have different z-coords as saved. 

This problem doesn't occure with "normal" placed objects.

**Comment by NeoArmageddon** [comment]
Fencer places objects with align to terrain normals. Other objects are placed without. Other objects aligned to normals "Ctrl + T" suffer the same problem.

Not related to fencer, but to bis_fnc_pitchBank.

**Comment by NeoArmageddon** [comment]
Fixed in 1.7 branch
