### ISSUE TITLE
Bug: Objects being sent to 0,0.

### ISSUE THREAD

**Issue by Twelvecaliber** [NeoArmageddon/MapBuilder#9]
Sometimes, for no apparent reason, whether it is spawning a fresh object, or copying and pasting and object, or selecting one placed down 10 minutes ago, keep having objects teleported to the 0,0 grid co-ordinates of the map. When selecting them the yellow bounding box draws off towards 0,0. Then when the object is attempted to be moved, it vanishes. When manually moving to 0,0 i can find all the dissapeared objects stuck in place, unable to be moved.

**Comment by Twelvecaliber** [comment]
Update: Found a select instance where this occurs, when, selecting an object that was placed in TB and is therefore permanently placed on the map, specifically fences and walls, and you try to copy and paste them, it creates this problem with the yellow bounding box drawing off to 0,0 and the object teleporting when clicked.

**Comment by NeoArmageddon** [comment]
Splendid discovery. That will be "autofixed" when I merge to the new selection mechanics.
